using Newtonsoft.Json;
using System;
using TeronEsirClient.Enums;
using TeronEsirClient.Json;

namespace TeronEsirClient.Models.Fiscalization.Read
{
    public sealed class TeronEsirInvoiceContents
    {
        public TeronEsirAdvancePayment[] AdvancePaidByTax { get; private set; } = Array.Empty<TeronEsirAdvancePayment>();
        public decimal? AdvancePaidTotalAmount { get; private set; }
        public TeronEsirAdvancePayment[] AdvancePayment { get; private set; } = Array.Empty<TeronEsirAdvancePayment>();
        public decimal? AdvanceRemainingAmount { get; private set; }
        public TeronEsirAdvancePayment[] AdvanceRemainingByTax { get; private set; }
        public decimal? AdvanceTaxTotalAmount { get; private set; }
        public bool AutoGenerated { get; private set; }
        public TeronEsirInvoiceRequest InvoiceRequest { get; private set; }
        public TeronEsirInvoiceResponse InvoiceResponse { get; private set; }
        public bool Print { get; private set; }

        [JsonProperty("receiptImageBase64", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ByteArrayBase64Converter))]
        public byte[] ReceiptImage { get; private set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(EnumStringConverter<ReceiptImageFormat>))]
        public ReceiptImageFormat? ReceiptImageFormat { get; private set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(EnumStringConverter<ReceiptLayout>))]
        public ReceiptLayout? ReceiptLayout { get; private set; }
        public bool RenderReceiptImage { get; private set; }
        public bool SkipEftPos { get; private set; }
        public bool SkipEftPosPrint { get; private set; }
        public TeronEsirPayment[] FiscalizedPayment { get; private set; }
        public bool IssueCopy { get; private set; }
        public int ReceiptSlipFontSizeLarge { get; private set; }
        public int ReceiptSlipFontSizeNormal { get; private set; }
    }
}
